sudo: true
language: node_js
node_js:
  - '10'

addons:
  apt:
    packages:
      - libgconf-2-4
  chrome: stable

branches:
  only:
    - /.*/

# Keep the npm cache around to speed up installs
cache:
  npm: true
  directories:
    - '$HOME/.npm'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

install:
  - pip install --user awscli
  - yarn install --production=false

before_script:
  - yarn bootstrap
  - yarn link

script:
  - yarn lint
  - yarn build
  - yarn doc
    - 'if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash scripts/publish.sh; fi'
  - 'if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then yarn deploy; fi'
  - yarn test

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish.sh
    on:
      branch: master

notifications:
  email:
    on_failure: always
